### ISSUE TITLE
how to pip install requirements file ?

### ISSUE THREAD

**Issue by kyunggyuyeol** [nfmcclure/tensorflow_cookbook#105]
how to pip install requirements file ?

i use Windows 10 64bit & python3.6

install cmd "pip install -r requirements.txt"  input 

  Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for tensorflow (from -r requirements.txt (line 1))

**Comment by nfmcclure** [comment]
Hi @kyunggyuyeol , thanks for the report and sorry for the late reply. I'm just now having time to triage and go through the issues.

This is very strange, TensorFlow does have a windows version.  You may try to install on your own with the instructions found here:

https://www.tensorflow.org/install/install_windows

Then try again.

If you are still running into problems, then I suspect you may need to update your pip library.

I'm going to close this issue.  If it still doesn't work, feel free to reopen.
