### ISSUE TITLE
1.0.0rc2 tensorflow has no attribute 'merge_all_summaries'

### ISSUE THREAD

**Issue by wegamekinglc** [nfmcclure/tensorflow_cookbook#11]
This error will show up when I run the example [02_tensors.ipynb](https://github.com/nfmcclure/tensorflow_cookbook/blob/master/01_Introduction/02_Creating_and_Using_Tensors/02_tensors.ipynb)

**Comment by nfmcclure** [comment]
Hi @wegamekinglc, The Tensorboard summary operations have depreciated and/or changed names with the 1.0.0 release.  I have not updated the code to reflect this yet.  But here are the changes for 1.0.0:
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

And here is a Tensorboard tutorial that has been updated:
https://www.tensorflow.org/how_tos/summaries_and_tensorboard/

You want to change the name of the function from `merge_all_summaries()` to `tf.summary.merge_all()`.  Be aware that there maybe other names you will need to update.

**Comment by nfmcclure** [comment]
I will keep this ticket open until I have fixed the code.  (Most likely this weekend). Thanks!

**Comment by wegamekinglc** [comment]
@nfmcclure Thank you for your helpful advice! I will follow these links. I am really enjoying these notebooks and can't wait for the book!

**Comment by nfmcclure** [comment]
Files should be fixed now. Thanks!
