### ISSUE TITLE
Exporting predicted value vs real value in 06_using_a_multiple_layer_network.ipynb

### ISSUE THREAD

**Issue by louisdv75** [nfmcclure/tensorflow_cookbook#111]
Hello!

I loved your notebook on Multiple Layer Network!

I would like to know if you could add (or tell me) what lines of code could let me check the predicted values vs the real ones in a CSV format?

Thanks!

**Comment by nfmcclure** [comment]
Hi @louisdv75 ,  Sorry about the late response. I'm just now getting around to updating all the code to current TF versions and Python 3.6.

I'm not entirely sure on your use case. I can add an evaluation script that loads X-values and Y-values from a CSV formatted file and outputs accuracy metrics with the predicted values.

Is that what you are looking for?

**Comment by nfmcclure** [comment]
Hi @louisdv75 ,  thanks for the suggestion. Sorry for the lateness, but you can find evaluation code for new points in the Multiple Layer Network in chapter six now. Thanks!  Let me know if you have any questions by reopening this issue.
