### ISSUE TITLE
Replace tf.initialize_all_variables() with tf.global_variables_initializer()?

### ISSUE THREAD

**Issue by mchirico** [nfmcclure/tensorflow_cookbook#12]
They seem to be making changes with TensorFlow

It looks like the following initialization should be used..

    init = tf.global_variables_initializer()

Below is the older code, which gives the following warning...

    init = tf.initialize_all_variables()

    WARNING:tensorflow:From <ipython-input-15-961de099ec6b>:61 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be 
    removed after 2017-03-02.

**Comment by nfmcclure** [comment]
Thanks!  I will update the code this weekend.

**Comment by nfmcclure** [comment]
Updated! Thanks.

**Comment by KingLei1993** [comment]
Thanks!  Updated!
