### ISSUE TITLE
08_logistic_regression #88 reopen for python 3 coding

### ISSUE THREAD

**Issue by davidabek1** [nfmcclure/tensorflow_cookbook#125]
03_Linear_Regression\08_Implementing_Logistic_Regression\08_logistic_regression.py
and also in the ipython notebook, same issue.

using csv writer, 
python 3 requires adding ",newline='' ",
in order not to get extra empty line within each line write.

line 40: with open(birth_weight_file, "w"**, newline=''**) as f:

without this update, you get an error after reading the file and trying to load it into the x_vals variable.

**Comment by nfmcclure** [comment]
This should be updated now, thanks!
