### ISSUE TITLE
Introductory CNN Model: MNIST Digits TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.

### ISSUE THREAD

**Issue by fanshius** [nfmcclure/tensorflow_cookbook#126]
The cause of this error is you are feeding two different type of data: tensor and numpy array. Try to either conver the y label to tensor or convert ran_x to np.array (by np.expand.dims)

**Comment by nfmcclure** [comment]
Thanks for noticing - I'll update this in the coming few months for the book v2.

**Comment by nfmcclure** [comment]
This should be fixed. Please repull and try again. If you still have an issue, feel free to reopen and also to let me know your TF version, Python version, and OS.  Thanks!
