### ISSUE TITLE
Formula error at Chapter 4 (Working with Linear SVM)

### ISSUE THREAD

**Issue by erichooi** [nfmcclure/tensorflow_cookbook#135]
![screen shot 2018-07-16 at 3 50 36 pm](https://user-images.githubusercontent.com/14349940/42747805-6ba46a7a-8910-11e8-926d-0f25b765ba3d.png)

Is that suppose to be **-** instead of **+**? This is a formula that I found on Wikipedia.

![screen shot 2018-07-16 at 3 54 20 pm](https://user-images.githubusercontent.com/14349940/42747878-ab0f7114-8910-11e8-95ad-0682a5c93f4e.png)

**Comment by nfmcclure** [comment]
Hi @erichooi ,
Thanks for asking.  I believe just a substitution of a negative b for a positive b will make the formulas equivalent.

But it is important in the results to remember that the b is negative and not positive.  I'll recheck the code for this. (I'll keep this issue open until I can check it).

But the formulas are equivalent under a negative-b substitution.

**Comment by nfmcclure** [comment]
Just went to go fix this.  I see what you mean now.  The code is correct, but the formula is wrong.  It's fixed in the jupyter notebook finally.  I'm going to close this. Feel free to reopen if I missed something.
