### ISSUE TITLE
Possible Error in build_vocab - 09_Recurrent_Neural_Networks/03_Implementing_LSTM/03_implementing_lstm.py

### ISSUE THREAD

**Issue by ychong** [nfmcclure/tensorflow_cookbook#138]
Hi, 

There appears to be a possible error in the build_vocab method (line 85) for the LSTM implementation in Chapter 03.

The build_vocab method seems to be mapping the words to an arbitrary increasing indexing instead of the actual word counts. 

If the intention is to create both vocab2ix and ix2vocab dictionaries of equal lengths, then it might make more sense to first sort the words (keys) by their counts (values) in an increasing manner than map it to an increasing index as per what you have done. By doing this, you are somewhat mapping vocab2ix to its word counts instead of an arbitrary indexing. You will also prevent yourself from removing some of the vocab/words since there might be multiple words with the same word count. I would like to suggest the following:  

Error (this maps the words/key to an arbitrary increasing ix and remove some of the words/vocabs):

> '# limit word counts
> word_counts = {key:val for key, val in word_counts.items() if val>min_word_freq}
> '# create vocab -> index mapping
> words = word_counts.keys()
> vocab_to_ix_dict = {key:(ix+1) for ix, key in enumerate(words)}

Corrected (we should first sort the words by their counts then assign them to ix):

> '# limit word counts 
> word_counts = {key:val for key, val in word_counts.items() if val>min_word_freq}
> '# first sort word counts by values/counts 
> import operator
> word_counts = sorted(word_counts.items(), key=operator.itemgetter(1))
> '# create vocab -> index mapping
> words = [x[0] for x in word_counts] # create a list instead to allow ordering 
> vocab_to_ix_dict = {key:(ix+1) for ix, key in enumerate(words)}

Please let me know if this is helpful. Again, I can be reached at chongyixiang@gmail.com

Sincerely, 
-Yi Xiang

**Comment by nfmcclure** [comment]
Hi @ychong !  Thanks for the question.
The important line is this:

`word_counts = {key:val for key, val in word_counts.items() if val>min_word_freq}`

This will limit the word-count dictionary to just words that appear more often than our cutoff (min_word_freq).

After that, it doesn't matter the order of words in our dictionary as long as both the ix2word and word2ix dictionaries map to the same index:word or word:index.  The indices just refer to a unique row in our embedding matrix.  It won't matter if the word "math" maps to the first row or the 205th row as long as we can keep track of which row it is at all times.

I believe both implementations (yours or mine) works.  The only advantage to yours is that the order is meaningful to look at.  Other than that, it will have no impact on the algorithm. (I'm 99% sure, but would be really interested if that is not the case).  Let me know if you actually find significant differences between the outcomes!

Feel free to reopen if you do.  I'm going to close this for now as I'm trying to clean up all the issues.
