### ISSUE TITLE
on what basis do we classify whether msg is spam or ham

### ISSUE THREAD

**Issue by vanipolnedi** [nfmcclure/tensorflow_cookbook#142]
i am new to rnn ...can u anyone please tell me where to give input msg and find whether it is spam or ham

**Comment by nfmcclure** [comment]
Hi @vanipolnedi ,
Thanks for the message.
Have you looked and read through the jupyter notebook here ([notebook link here](https://github.com/nfmcclure/tensorflow_cookbook/blob/master/09_Recurrent_Neural_Networks/02_Implementing_RNN_for_Spam_Prediction/02_implementing_rnn.ipynb) ) ?

If you're asking about how RNNs work in general, I recommend reading through these resources:

- http://www.wildml.com/2015/09/recurrent-neural-networks-tutorial-part-1-introduction-to-rnns/
- http://slazebni.cs.illinois.edu/spring17/lec02_rnn.pdf

I hope that helps.

I'm going to close this issue for now.  If you have any specific questions about the code or requests, please re open.  Thanks!

**Comment by vanipolnedi** [comment]
@nfmcclure  thanks for the immediate response . in that code, i am unable to understand where to give input msg to test whether it is spam or ham.
