### ISSUE TITLE
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by zhangdm** [nfmcclure/tensorflow_cookbook#20]
> when I run the chapter8：08_Convolutional_Neural_Networks，02_Intro_to_CNN_MNIST ,the example give me a error ,I don't know how to sovle.

# the error as follow:

ValueError                                Traceback (most recent call last)
<ipython-input-2-a88ef5ecd2c2> in <module>()
    109 
    110 # Declare Loss Function (softmax cross entropy)
--> 111 loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(model_output, y_target))
    112 
    113 # Create a prediction function

E:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py in sparse_softmax_cross_entropy_with_logits(_sentinel, labels, logits, name)
   1682   """
   1683   _ensure_xent_args("sparse_softmax_cross_entropy_with_logits", _sentinel,
-> 1684                     labels, logits)
   1685 
   1686   # TODO(pcmurray) Raise an error when the label is not an index in

E:\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py in _ensure_xent_args(name, sentinel, labels, logits)
   1531   if sentinel is not None:
   1532     raise ValueError("Only call `%s` with "
-> 1533                      "named arguments (labels=..., logits=..., ...)" % name)
   1534   if labels is None or logits is None:
   1535     raise ValueError("Both labels and logits must be provided.")

ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by zhangdm** [comment]
My tensorflow version is 1.0 with cpu

**Comment by yingwei13mei** [comment]
Cause tensorflow version has been updated to Ver 1.0 and the sparse_softmax_cross_entropy_with_logits  function's parameter have been reinforced to be added  logits=, ..labels= . You could modify with tf.nn.sparse_softmax_cross_entropy_with_logits(logist=model_output, labels=y_target)). It could be work

**Comment by nfmcclure** [comment]
Will merge this over the weekend.  Thanks for bringing to my attention.

**Comment by nfmcclure** [comment]
I have this working now.  If you still run into an error, please comment/reopen and also leave the OS, python version, and TensorFlow version.  Thanks!

**Comment by wdurnoUBC** [comment]
I have this bug for a later version.
logits = model_output, labels=y_placeholder

VERSIONS:
OS: Ubuntu 16.04
TF: 1.2.1, GPU
Python: 2.7.13

DEBUG:
>>> cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1555, in softmax_cross_entropy_with_logits
    labels, logits)
  File "/home/me/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1512, in _ensure_xent_args
    raise ValueError("Both labels and logits must be provided.")
ValueError: Both labels and logits must be provided.

**Comment by FelipeMeganha** [comment]
Try

cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))
