### ISSUE TITLE
tf.nn.seq2seq. cannot be found with tf version 1.0

### ISSUE THREAD

**Issue by yingwei13mei** [nfmcclure/tensorflow_cookbook#21]
In 09_Recurrent_Neural_Networks\03_Implementing_LSTM\03_implementing_lstm.py ,
there could not find seq2seq. I think maybe update to version 1.0 of tf caused this problem.
"
--> 166         decoder = tf.nn.seq2seq.rnn_decoder
    167         outputs, last_state = decoder(rnn_inputs_trimmed,
    168                                       self.initial_state,

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'
"

**Comment by nfmcclure** [comment]
Two things are now apparent to me.
(1) TensorFlow's automatic upgrade script that upgrades python code to be 1.0.0 compliant does not address all issues.
(2) The seq2seq functions have changed dramatically.

After a bit of digging, it appears the `seq2seq` functions are in the following location:

``` tf.contrib.seq2seq```

I would try the function: `tf.contrib.seq2seq.simple_decoder_fn_train()` for the training and `tf.contrib.seq2seq.simple_decoder_fn_inference()` for evaluation.

If that fails, you can also try `tf.contrib.seq2seq.dynamic_rnn_decoder()`, but read up on the documentation for that on the arguments.

I will attempt to go through all of chapter 9's code this weekend, as time permits.  Thanks!

**Comment by nfmcclure** [comment]
I was able to get this script working and also create a jupyter notebook in the process. It should work now.  For reference, I'm running Python 3.6.0 and TensorFlow 1.0.1.  If you are still running into errors, please let me know and also post your Python/TensorFlow version numbers.  Thanks!

**Comment by spongejj** [comment]
Why i run my code in  tensorflow 0.12.0 still meet this error?
module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'
