### ISSUE TITLE
The solution when 02_TensorFlow_way , 02_layering_nested_... can't work

### ISSUE THREAD

**Issue by leigaoyi** [nfmcclure/tensorflow_cookbook#22]
I'm not sure how many people have the same problem with me, when to finish the 02_layering_nested_operations. In my version , the default type of numpy and the constant of tensorflow is not the same. So when you meet the problem, you can try to use np.float32 or dtype=tf.float32, to make sure all variables have the same types to help sess.run() .

Love this cookbook!
and a suggestion. The last part in 02_Tensorflow_... can be replaced as:

merged = tf.summary.merge_all()
if not os.path.exists('tensorboard_logs/'):
    os.makedirs('tensorboard_logs/')

my_writer = tf.summary.FileWriter('tensorboard_logs/', sess.graph)

**Comment by leigaoyi** [comment]
This replace replies to Tensorflow 1.0.0

**Comment by nfmcclure** [comment]
I have this working now and have updated the repository.  Let me know if you still run into problems and if so, please also post your Python and TensorFlow version numbers.  Thanks!
