### ISSUE TITLE
ImportError: No module named 'tensorflow.models.rnn' cannot import data_utils

### ISSUE THREAD

**Issue by yingwei13mei** [nfmcclure/tensorflow_cookbook#24]
In 09_Recurrent_Neural_Networks\05_Creating_A_Sequence_To_Sequence_Model
05_seq2seq_translation.py
There was some import error as follows:
ImportError                               Traceback (most recent call last)
<ipython-input-4-de9ce88ac281> in <module>()
     21 from zipfile import ZipFile
     22 from collections import Counter
---> 23 from tensorflow.models.rnn.translate import data_utils
     24 from tensorflow.models.rnn.translate import seq2seq_model
     25 from tensorflow.python.framework import ops

ImportError: No module named 'tensorflow.models.rnn'

And could you please give me some suggestion about how to find the right module in ver 1.0 after the update changed

**Comment by nfmcclure** [comment]
TensorFlow's `upgrade to v1.0.0` conversion script does not appear to have worked with the RNN library.  TF v 1.0 has moved the RNN library.  I will address this over the weekend.

**Comment by nfmcclure** [comment]
I think I have the solution.  But it depends on a pull request that has recently been merged into the TensorFlow code base.  It will not be available until the next version release of TensorFlow.  Which should be soon.  Stay tuned.

**Comment by nfmcclure** [comment]
Finally TF released a new version and I was able to get it working.  Please upgrade to TF v1.1.0 + and re try with the newer code.  Thanks!
