### ISSUE TITLE
ipython notebook tensorboard outputs

### ISSUE THREAD

**Issue by slcott** [nfmcclure/tensorflow_cookbook#27]
Looks like the ipynb files are using some deprecated functions:

For section: **Create and Format Tensorboard outputs for viewing**

Error:
> AttributeError                            Traceback (most recent call last)
<ipython-input-9-961aa540430d> in <module>()
----> 1 merged = tf.merge_all_summaries()
      2 
      3 if not os.path.exists('tensorboard_logs/'):
      4     os.makedirs('tensorboard_logs/')
      5 

> AttributeError: module 'tensorflow' has no attribute 'merge_all_summaries'

the following change fixes it:
```
# merged = tf.merge_all_summaries()
merged = tf.summary.merge_all(key='summaries')
```

Error:
> AttributeError                            Traceback (most recent call last)
<ipython-input-12-35196dde9972> in <module>()
      6 
      7 
----> 8 my_writer = tf.train.SummaryWriter('tensorboard_logs/', sess.graph)
      9 # my_writer = tf.summary.FileWriter('tensorboard_logs/', sess.graph)

> AttributeError: module 'tensorflow.python.training.training' has no attribute 'SummaryWriter'

the following change fixes it:
```
# my_writer = tf.train.SummaryWriter('tensorboard_logs/', sess.graph)
my_writer = tf.summary.FileWriter('tensorboard_logs/', sess.graph)
```

**Comment by slcott** [comment]
Here's a PR https://github.com/nfmcclure/tensorflow_cookbook/pull/28

**Comment by nfmcclure** [comment]
Thanks! Merged.
