### ISSUE TITLE
In the multi-class classification with SVM example code, "reshape_mul" function's last line should be return(tf.batch_matmul(v2, v1)) rather than tf.matmul(v2,v1)

### ISSUE THREAD

**Issue by ZenithFZH** [nfmcclure/tensorflow_cookbook#31]

**Comment by nfmcclure** [comment]
Hi @ZenithFZH,

I think you may be on an older version of TensorFlow.  As of version 0.12 and forward, the function `tf.batch_matmul` has been removed in favor of `tf.matmul`.

I recommend upgrading your TensorFlow version and retry.

I created a jupyter notebook from the code as well in the same directory.

**Comment by nfmcclure** [comment]
For reference, see this TF issue:

https://github.com/tensorflow/tensorflow/issues/6560
