### ISSUE TITLE
Error at chapter 7 Working with CBOW Embeddings

### ISSUE THREAD

**Issue by sigmoidx** [nfmcclure/tensorflow_cookbook#32]
Hi, there are some errors in the CBOW example but this one is something I can't solve.

Traceback (most recent call last):
  File "05_Working_With_CBOW.py", line 125, in <module>
    window_size, method='cbow')
  File "/home/test/cbow/text_helpers.py", line 97, in generate_batch_data
    batch, labels = [list(x) for x in zip(*batch_and_labels)]
ValueError: not enough values to unpack (expected 2, got 0)

Thanks,

**Comment by nfmcclure** [comment]
HI @sigmoidx,  thanks for the alert.  I suspect this is due to the TF v 1 upgrade issues that everyone is experiencing.  I have tackled a few tonight, but haven't gotten around the the NLP chapter yet.  I will probably get around to this in the next week or two.

**Comment by nfmcclure** [comment]
Hi @sigmoidx, This should be fixed now.  Also, fixed in all the chapter 7 code and each example in chapter 7 now has a jupyter notebook. Thanks and let me know if you have any more problems.

**Comment by sigmoidx** [comment]
Thanks for fixing errors!!! I will test them ASAP.
