### ISSUE TITLE
The switch problem in jupyter notebook .

### ISSUE THREAD

**Issue by leigaoyi** [nfmcclure/tensorflow_cookbook#35]
When I finish one example, then switch to another. My jupyter notebook shows the problem 
**The kernel appears to die**
Restart can't help, and I have to close all of them. After **restarting jupyter notebook** and run into the same example, it can work. But do this is not comfortable. Why my condition happens?

**Comment by leigaoyi** [comment]
I'm afraid I find the problem, if I shutdown the special notebook in the running part, then I switch to another won't make problems. Oh, how quickly I find it. 
The tensorflow or the computation sources just can't be called at two more notebooks.

**Comment by nfmcclure** [comment]
Hi @leigaoyi ,  Thanks for reporting this.  Can you give me a bit more details?  Which script or scripts are you trying to run?  Can you post the full Jupyter Kernel traceback?  Thanks!

**Comment by leigaoyi** [comment]
I think I solve the problem , by fully shutdown the former notebook , then the newer open one can run normally. So no more notebooks can run at the same time in my computer. 

My Jupyter is 1.0.0 , and my notebook is 4.4.1

**Comment by leigaoyi** [comment]
I think I solve the problem , by fully shutdown the former notebook , then the newer open one can run normally. So no more notebooks can run at the same time in my computer. 

My Jupyter is 1.0.0 , and my notebook is 4.4.1
