### ISSUE TITLE
06_multiclass_svm.py ValueError: Dimensions

### ISSUE THREAD

**Issue by duongtu** [nfmcclure/tensorflow_cookbook#41]
Python 3.5
Tensorflow GPU 1.0.1
Commit: 69396a0999e52208d321149783fcccf6a56c3bd1

File: 06_multiclass_svm.py
Line: 74
second_term = tf.reduce_sum(tf.multiply(my_kernel, tf.multiply(b_vec_cross, y_target_cross)),[1,2])

Error:
ValueError: Dimensions must be equal, but are 2 and 3 for 'Mul_3' (op: 'Mul') with input shapes: [2,?,1], [3,50,50].

**Comment by nfmcclure** [comment]
Hi @duongtu ,  Thanks for posting this.  I had the updated jupyter notebook, but didn't update the python script.  I made the necessary changes and the python script is fixed.

I suggest you repull the python script and try again with the recent changes.  Let me know if that does not work.

**Comment by duongtu** [comment]
Thanks @nfmcclure
