### ISSUE TITLE
Missing CIFAR-10 Image Data

### ISSUE THREAD

**Issue by mclarknc** [nfmcclure/tensorflow_cookbook#75]
/01_Introduction/07_Working_with_Data_Sources/ is missing a link to the CIFAR-10 dataset

**Comment by zhedongzheng** [comment]
You can use built-in keras in tensorflow to obtain the dataset in one line of code
```python
(X_train, y_train), (X_test, y_test) = tf.contrib.keras.datasets.cifar10.load_data()
```

**Comment by nfmcclure** [comment]
Thanks @zhedongzheng !  I'll update a link to it soon.  If, on the other hand, you are looking for information on the CIFAR datasets, check:
https://www.cs.toronto.edu/~kriz/cifar.html

**Comment by nfmcclure** [comment]
I added links, the specified Keras commands, and a sample image plot in the working_with_data_sources.  Let me know if you want more information. Thanks!
