### ISSUE TITLE
06_Neural_Networks/06_using_a_multiple_layer_network.ipynb (list index out of range)

### ISSUE THREAD

**Issue by mrStasSmirnoff** [nfmcclure/tensorflow_cookbook#78]
During compiling following piece of code:
-----------------------------------------------------------------------------------------------------
birth_weight_file = 'birth_weight.csv'

# download data and create data file if file does not exist in current directory
if not os.path.exists(birth_weight_file):
    birthdata_url = 'https://github.com/nfmcclure/tensorflow_cookbook/raw/master/01_Introduction/07_Working_with_Data_Sources/birthweight_data/birthweight.dat'
    birth_file = requests.get(birthdata_url)
    birth_data = birth_file.text.split('\r\n')
    birth_header = birth_data[0].split('\t')
    birth_data = [[float(x) for x in y.split('\t') if len(x)>=1] for y in birth_data[1:] if len(y)>=1]
    with open(birth_weight_file, "w") as f:
        writer = csv.writer(f)
        writer.writerows(birth_data)
        f.close()

# read birth weight data into memory
birth_data = []
with open(birth_weight_file, newline='') as csvfile:
     csv_reader = csv.reader(csvfile)
     birth_header = next(csv_reader)
     for row in csv_reader:
         birth_data.append(row)

birth_data = [[float(x) for x in row] for row in birth_data]

y_vals = np.array([x[10] for x in birth_data])

---------------------------------------------------------------------------------------------------------
I faced a problem:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-45c1f733edd6> in <module>()
     28 
     29 # Extract y-target (birth weight)
---> 30 y_vals = np.array([x[10] for x in birth_data])

<ipython-input-12-45c1f733edd6> in <listcomp>(.0)
     28 
     29 # Extract y-target (birth weight)
---> 30 y_vals = np.array([x[10] for x in birth_data])

IndexError: list index out of range
--------------------------------------------------------------------------
It is obviously because 

print(birth_data[10]) is given as empty row. However, I do not know fix it, could please someone help me?

I am new in python before I was working with Matlab and a little bit with C++, therefore a piece of code which is responsible for '# download data and creates data file if file does not exist in current directory'
is quite unclear. I will be extremely thankful if someone explains briefly what is happing there.

**Comment by jimthompson5802** [comment]
@mrStasSmirnoff Looks like the cause of the problem is the data set retrieved has a different format from when the code was originally written.  Originally the data set had 11 columns, now the data set has 9 columns.  To fix your immediate problem, I suggest changing the line of code to read:
```
y_vals = np.array([x[8] for x in birth_data])
```

You should also change this line:
```
cols_of_interest = ['AGE', 'LWT', 'RACE', 'SMOKE', 'PTL', 'HT', 'UI', 'FTV']
```
to read:
```
cols_of_interest = ['AGE', 'LWT', 'RACE', 'SMOKE', 'PTL', 'HT', 'UI']
```

**Comment by jimthompson5802** [comment]
@nfmcclure in addition to the code identified above, some other changes, e.g., placeholder and input layer shape specifications, are needed to accommodate the new raw data format.  I'm working on the fixes.
