### ISSUE TITLE
08_logistic_regression

### ISSUE THREAD

**Issue by SatoshiRobatoFujimoto** [nfmcclure/tensorflow_cookbook#88]
I just tried 08_logistic_regression code. However, I got the error in follows.
Give me some advice?

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-188d7dcac03d> in <module>()
     26 
     27 # Pull out target variable
---> 28 y_vals = np.array([x[1] for x in birth_data])
     29 # Pull out predictor variables (not id, not target, and not birthweight)
     30 x_vals = np.array([x[2:9] for x in birth_data])

<ipython-input-17-188d7dcac03d> in <listcomp>(.0)
     26 
     27 # Pull out target variable
---> 28 y_vals = np.array([x[1] for x in birth_data])
     29 # Pull out predictor variables (not id, not target, and not birthweight)
     30 x_vals = np.array([x[2:9] for x in birth_data])

IndexError: list index out of range

**Comment by nfmcclure** [comment]
Hi @SatoshiRobatoFujimoto ,  Thanks for noticing this!  The birthweight data source changed, and I decided to host a slightly different version of it here on github.  This file didn't get the changes it needed.  I fixed both the python file and jupyter notebook.  They both should be working now. Please repull the code and check if you would like.  Also, please reopen the ticket if you are getting the same error. Thanks!
