### ISSUE TITLE
running error in 09_Recurrent_Neural_Networks/05 seq2seq

### ISSUE THREAD

**Issue by lyan62** [nfmcclure/tensorflow_cookbook#91]
when defining translate_model, running this cell:

```
print('Creating Translation Model')
input_vocab_size = vocab_size
output_vocab_size = vocab_size

translate_model = translation_model(sess=sess,
                                    input_vocab_size=vocab_size,
                                    output_vocab_size=vocab_size,
                                    buckets=buckets,
                                    rnn_size=rnn_size,
                                    num_layers=num_layers,
                                    max_gradient=max_gradient,
                                    learning_rate=learning_rate,
                                    lr_decay_rate=lr_decay_rate,
                                    forward_only=False)

# Tell TensorFlow to reuse the variables for the test model
with tf.variable_scope(tf.get_variable_scope(), reuse=True):
    #Reuse the variables for the test model
    test_model = translation_model(sess=sess,
                                    input_vocab_size=vocab_size,
                                    output_vocab_size=vocab_size,
                                    buckets=buckets,
                                    rnn_size=rnn_size,
                                    num_layers=num_layers,
                                    max_gradient=max_gradient,
                                    learning_rate=learning_rate,
                                    lr_decay_rate=lr_decay_rate,
                                    forward_only=True)
    test_model.batch_size = 1


```
I got error as:

> AttributeErrorTraceback (most recent call last)
> <ipython-input-23-d80c8e004260> in <module>()
>      12                                     learning_rate=learning_rate,
>      13                                     lr_decay_rate=lr_decay_rate,
> ---> 14                                     forward_only=False)
>      15 
>      16 # Tell TensorFlow to reuse the variables for the test model
> 
> <ipython-input-22-ba700daa3a1e> in translation_model(sess, input_vocab_size, output_vocab_size, buckets, rnn_size, num_layers, max_gradient, learning_rate, lr_decay_rate, forward_only)
>      14           lr_decay_rate,
>      15           forward_only=forward_only,
> ---> 16           dtype=tf.float32)
>      17     return(model)
> 
> /home/wenyanli/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in __init__(self, source_vocab_size, target_vocab_size, buckets, size, num_layers, max_gradient_norm, batch_size, learning_rate, learning_rate_decay_factor, use_lstm, num_samples, forward_only, dtype)
>     177           self.target_weights, buckets,
>     178           lambda x, y: seq2seq_f(x, y, False),
> --> 179           softmax_loss_function=softmax_loss_function)
>     180 
>     181     # Gradients and SGD update operation for training the model.
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.pyc in model_with_buckets(encoder_inputs, decoder_inputs, targets, weights, buckets, seq2seq, softmax_loss_function, per_example_loss, name)
>    1204           variable_scope.get_variable_scope(), reuse=True if j > 0 else None):
>    1205         bucket_outputs, _ = seq2seq(encoder_inputs[:bucket[0]],
> -> 1206                                     decoder_inputs[:bucket[1]])
>    1207         outputs.append(bucket_outputs)
>    1208         if per_example_loss:
> 
> /home/wenyanli/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in <lambda>(x, y)
>     176           self.encoder_inputs, self.decoder_inputs, targets,
>     177           self.target_weights, buckets,
> --> 178           lambda x, y: seq2seq_f(x, y, False),
>     179           softmax_loss_function=softmax_loss_function)
>     180 
> 
> /home/wenyanli/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in seq2seq_f(encoder_inputs, decoder_inputs, do_decode)
>     140           output_projection=output_projection,
>     141           feed_previous=do_decode,
> --> 142           dtype=dtype)
>     143 
>     144     # Feeds for inputs.
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.pyc in embedding_attention_seq2seq(encoder_inputs, decoder_inputs, cell, num_encoder_symbols, num_decoder_symbols, embedding_size, num_heads, output_projection, feed_previous, dtype, scope, initial_state_attention)
>     846     dtype = scope.dtype
>     847     # Encoder.
> --> 848     encoder_cell = copy.deepcopy(cell)
>     849     encoder_cell = core_rnn_cell.EmbeddingWrapper(
>     850         encoder_cell,
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     172             copier = getattr(x, "__deepcopy__", None)
>     173             if copier:
> --> 174                 y = copier(memo)
>     175             else:
>     176                 reductor = dispatch_table.get(cls)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/site-packages/tensorflow/python/layers/base.pyc in __deepcopy__(self, memo)
>     474         setattr(result, k, copy.copy(v))
>     475       else:
> --> 476         setattr(result, k, copy.deepcopy(v, memo))
>     477     return result
>     478 
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_list(x, memo)
>     228     memo[id(x)] = y
>     229     for a in x:
> --> 230         y.append(deepcopy(a, memo))
>     231     return y
>     232 d[list] = _deepcopy_list
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_list(x, memo)
>     228     memo[id(x)] = y
>     229     for a in x:
> --> 230         y.append(deepcopy(a, memo))
>     231     return y
>     232 d[list] = _deepcopy_list
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     332     if state is not None:
>     333         if deep:
> --> 334             state = deepcopy(state, memo)
>     335         if hasattr(y, '__setstate__'):
>     336             y.__setstate__(state)
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_list(x, memo)
>     228     memo[id(x)] = y
>     229     for a in x:
> --> 230         y.append(deepcopy(a, memo))
>     231     return y
>     232 d[list] = _deepcopy_list
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_tuple(x, memo)
>     235     y = []
>     236     for a in x:
> --> 237         y.append(deepcopy(a, memo))
>     238     d = id(x)
>     239     try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     161     copier = _deepcopy_dispatch.get(cls)
>     162     if copier:
> --> 163         y = copier(x, memo)
>     164     else:
>     165         try:
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _deepcopy_dict(x, memo)
>     255     memo[id(x)] = y
>     256     for key, value in x.iteritems():
> --> 257         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     258     return y
>     259 d[dict] = _deepcopy_dict
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in deepcopy(x, memo, _nil)
>     188                             raise Error(
>     189                                 "un(deep)copyable object of type %s" % cls)
> --> 190                 y = _reconstruct(x, rv, 1, memo)
>     191 
>     192     memo[d] = y
> 
> /home/wenyanli/anaconda2/envs/cookbook/lib/python2.7/copy.pyc in _reconstruct(x, info, deep, memo)
>     341                 slotstate = None
>     342             if state is not None:
> --> 343                 y.__dict__.update(state)
>     344             if slotstate is not None:
>     345                 for key, value in slotstate.iteritems():
> 
> AttributeError: 'NoneType' object has no attribute 'update'
> 

previous codes all work fine.  How can I get this code work?

**Comment by nfmcclure** [comment]
Hi @lyan62 ,  thanks for bringing this to my attention.  Unfortunately, it runs on my system.  From the error logs, it appears you are running this with Python 2.7.  This whole book was written in Python 3.5+ (Python 3.6 recommended).  I suggest you upgrade your python version and try again along with the most current version of Tensorflow (tested for v1.2).

I highly recommend upgrading to Python 3.6 for all your programming needs. The reasons for this are (1) the python community is moving to python 3 and python 2 will be defunct in 2020, (2) Most (if not all) new python libraries are being developed in python 3, and (3) python 3.5+ brings great speed and efficiency improvements.

I'm going to close this issue for now, but if after upgrading, the problem persists, please reopen and paste your (a) Python version, (b) TensorFlow version (also if gpu or cpu based), (c) operating system, and (4) the full traceback like you did above.  Good luck and thanks!
