### ISSUE TITLE
I would like to request your permission as author so that I can translate some parts of your book 

### ISSUE THREAD

**Issue by AlisterTA** [nfmcclure/tensorflow_cookbook#92]
Dear Nick,
I started reading your book entitled “TensorFlow Machine Learning Cookbook” about a month ago, and I should say it's a well-written book.

I really liked some of the ideas that you wrote and I would like to share them with students in my country.  I would like to request your permission as author so that I can translate some parts of your book into the Persian language with some modifications.  The modifications are required to provide context to ensure the translation is understood correctly. I am not doing this for financial gain; I would just like students in my country become more familiar with the topic and your book provides an excellent resource on this subject.  Needless to say, I will keep all links and give proper attribution to you as the author.  The translated sections will be published on my blog, and I can provide you with the link once complete.  

I really appreciate you considering my request.  If you have any questions regarding the intent of my translation or the exact sections I wish to translate, please do not hesitate to ask.  I look forward to receiving your response.

**Comment by nfmcclure** [comment]
Hi @AlisterTA , thanks for your interest! It is fine if you want to translate it.  I appreciated you intentions and feel free to translate the text and use the Python scripts you find here.  Please let me know if I can provide clarification on anything in the process.  I'm going to close this issue and please reopen it if you have any questions.  Thanks!
