### ISSUE TITLE
Error running 09 Recurrent_Neural_Networks/05_seq2seq

### ISSUE THREAD

**Issue by lyan62** [nfmcclure/tensorflow_cookbook#94]
When running:
```
print('Creating Translation Model')
input_vocab_size = vocab_size
output_vocab_size = vocab_size

translate_model = translation_model(sess=sess,
                                    input_vocab_size=vocab_size,
                                    output_vocab_size=vocab_size,
                                    buckets=buckets,
                                    rnn_size=rnn_size,
                                    num_layers=num_layers,
                                    max_gradient=max_gradient,
                                    learning_rate=learning_rate,
                                    lr_decay_rate=lr_decay_rate,
                                    forward_only=False)

# Tell TensorFlow to reuse the variables for the test model
with tf.variable_scope(tf.get_variable_scope(), reuse=True):
    #Reuse the variables for the test model
    test_model = translation_model(sess=sess,
                                    input_vocab_size=vocab_size,
                                    output_vocab_size=vocab_size,
                                    buckets=buckets,
                                    rnn_size=rnn_size,
                                    num_layers=num_layers,
                                    max_gradient=max_gradient,
                                    learning_rate=learning_rate,
                                    lr_decay_rate=lr_decay_rate,
                                    forward_only=True)
    test_model.batch_size = 1
    
```
    
Got output:

>    
>     Creating Translation Model
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-d80c8e004260> in <module>()
>      12                                     learning_rate=learning_rate,
>      13                                     lr_decay_rate=lr_decay_rate,
> ---> 14                                     forward_only=FCreating Translation Model
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-d80c8e004260> in <module>()
>      12                                     learning_rate=learning_rate,
>      13                                     lr_decay_rate=lr_decay_rate,
> ---> 14                                     forward_only=False)
>      15 
>      16 # Tell TensorFlow to reuse the variables for the test model
> 
> <ipython-input-11-ba700daa3a1e> in translation_model(sess, input_vocab_size, output_vocab_size, buckets, rnn_size, num_layers, max_gradient, learning_rate, lr_decay_rate, forward_only)
>      14           lr_decay_rate,
>      15           forward_only=forward_only,
> ---> 16           dtype=tf.float32)
>      17     return(model)
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in __init__(self, source_vocab_size, target_vocab_size, buckets, size, num_layers, max_gradient_norm, batch_size, learning_rate, learning_rate_decay_factor, use_lstm, num_samples, forward_only, dtype)
>     177           self.target_weights, buckets,
>     178           lambda x, y: seq2seq_f(x, y, False),
> --> 179           softmax_loss_function=softmax_loss_function)
>     180 
>     181     # Gradients and SGD update operation for training the model.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in model_with_buckets(encoder_inputs, decoder_inputs, targets, weights, buckets, seq2seq, softmax_loss_function, per_example_loss, name)
>    1204           variable_scope.get_variable_scope(), reuse=True if j > 0 else None):
>    1205         bucket_outputs, _ = seq2seq(encoder_inputs[:bucket[0]],
> -> 1206                                     decoder_inputs[:bucket[1]])
>    1207         outputs.append(bucket_outputs)
>    1208         if per_example_loss:
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in <lambda>(x, y)
>     176           self.encoder_inputs, self.decoder_inputs, targets,
>     177           self.target_weights, buckets,
> --> 178           lambda x, y: seq2seq_f(x, y, False),
>     179           softmax_loss_function=softmax_loss_function)
>     180 
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in seq2seq_f(encoder_inputs, decoder_inputs, do_decode)
>     140           output_projection=output_projection,
>     141           feed_previous=do_decode,
> --> 142           dtype=dtype)
>     143 
>     144     # Feeds for inputs.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in embedding_attention_seq2seq(encoder_inputs, decoder_inputs, cell, num_encoder_symbols, num_decoder_symbols, embedding_size, num_heads, output_projection, feed_previous, dtype, scope, initial_state_attention)
>     846     dtype = scope.dtype
>     847     # Encoder.
> --> 848     encoder_cell = copy.deepcopy(cell)
>     849     encoder_cell = core_rnn_cell.EmbeddingWrapper(
>     850         encoder_cell,
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     159             copier = getattr(x, "__deepcopy__", None)
>     160             if copier:
> --> 161                 y = copier(memo)
>     162             else:
>     163                 reductor = dispatch_table.get(cls)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/python/layers/base.py in __deepcopy__(self, memo)
>     474         setattr(result, k, copy.copy(v))
>     475       else:
> --> 476         setattr(result, k, copy.deepcopy(v, memo))
>     477     return result
>     478 
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_list(x, memo, deepcopy)
>     213     append = y.append
>     214     for a in x:
> --> 215         append(deepcopy(a, memo))
>     216     return y
>     217 d[list] = _deepcopy_list
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     167                     reductor = getattr(x, "__reduce_ex__", None)
>     168                     if reductor:
> --> 169                         rv = reductor(4)
>     170                     else:
>     171                         reductor = getattr(x, "__reduce__", None)
> 
> TypeError: can't pickle _thread.lock objectsalse)
>      15 
>      16 # Tell TensorFlow to reuse the variables for the test model
> 
> <ipython-input-11-ba700daa3a1e> in translation_model(sess, input_vocab_size, output_vocab_size, buckets, rnn_size, num_layers, max_gradient, learning_rate, lr_decay_rate, forward_only)
>      14           lr_decay_rate,
>      15           forward_only=forward_only,
> ---> 16           dtype=tf.float32)
>      17     return(model)
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in __init__(self, source_vocab_size, target_vocab_size, buckets, size, num_layers, max_gradient_norm, batch_size, learning_rate, learning_rate_decay_factor, use_lstm, num_samples, forward_only, dtype)
>     177           self.target_weights, buckets,
>     178           lambda x, y: seq2seq_f(x, y, False),
> --> 179           softmax_loss_function=softmax_loss_function)
>     180 
>     181     # Gradients and SGD update operation for training the model.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in model_with_buckets(encoder_inputs, decoder_inputs, targets, weights, buckets, seq2seq, softmax_loss_function, per_example_loss, name)
>    1204           variable_scope.get_variable_scope(), reuse=True if j > 0 else None):
>    1205         bucket_outputs, _ = seq2seq(encoder_inputs[:bucket[0]],
> -> 1206                                     decoder_inputs[:bucket[1]])
>    1207         outputs.append(bucket_outputs)
>    1208         if per_example_loss:
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in <lambda>(x, y)
>     176           self.encoder_inputs, self.decoder_inputs, targets,
>     177           self.target_weights, buckets,
> --> 178           lambda x, y: seq2seq_f(x, y, False),
>     179           softmax_loss_function=softmax_loss_function)
>     180 
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in seq2seq_f(encoder_inputs, decoder_inputs, do_decode)
>     140           output_projection=output_projection,
>     141           feed_previous=do_decode,
> --> 142           dtype=dtype)
>     143 
>     144     # Feeds for inputs.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in embedding_attention_seq2seq(encoder_inputs, decoder_inputs, cell, num_encoder_symbols, num_decoder_symbols, embedding_size, num_heads, output_projection, feed_previous, dtype, scope, initial_state_attention)
>     846     dtype = scope.dtype
>     847     # Encoder.
> --> 848     encoder_cell = copy.deepcopy(cell)
>     849     encoder_cell = core_rnn_cell.EmbeddingWrapper(
>     850         encoder_cell,
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     159             copier = getattr(x, "__deepcopy__", None)
>     160             if copier:
> --> 161                 y = copier(memo)
>     162             else:
>     163                 reductor = dispatch_table.get(cls)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/python/layers/base.py in __deepcopy__(self, memo)
>     474         setattr(result, k, copy.copy(v))
>     475       else:
> --> 476         setattr(result, k, copy.deepcopy(v, memo))
>     477     return result
>     478 
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_list(x, memo, deepcopy)
>     213     append = y.append
>     214     for a in x:
> --> 215         append(deepcopy(a, memo))
>     216     return y
>     217 d[list] = _deepcopy_list
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     167                     reductor = getattr(x, "__reduce_ex__", None)
>     168                     if reductor:
> --> 169                         rv = reductor(4)
>     170                     else:
>     171                         reductor = getattr(x, "__reduce__", None)
> 
> TypeError: can't pickle _thread.lock objects
>     
> Creating Translation Model
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-d80c8e004260> in <module>()
>      12                                     learning_rate=learning_rate,
>      13                                     lr_decay_rate=lr_decay_rate,
> ---> 14                                     forward_only=False)
>      15 
>      16 # Tell TensorFlow to reuse the variables for the test model
> 
> <ipython-input-11-ba700daa3a1e> in translation_model(sess, input_vocab_size, output_vocab_size, buckets, rnn_size, num_layers, max_gradient, learning_rate, lr_decay_rate, forward_only)
>      14           lr_decay_rate,
>      15           forward_only=forward_only,
> ---> 16           dtype=tf.float32)
>      17     return(model)
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in __init__(self, source_vocab_size, target_vocab_size, buckets, size, num_layers, max_gradient_norm, batch_size, learning_rate, learning_rate_decay_factor, use_lstm, num_samples, forward_only, dtype)
>     177           self.target_weights, buckets,
>     178           lambda x, y: seq2seq_f(x, y, False),
> --> 179           softmax_loss_function=softmax_loss_function)
>     180 
>     181     # Gradients and SGD update operation for training the model.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in model_with_buckets(encoder_inputs, decoder_inputs, targets, weights, buckets, seq2seq, softmax_loss_function, per_example_loss, name)
>    1204           variable_scope.get_variable_scope(), reuse=True if j > 0 else None):
>    1205         bucket_outputs, _ = seq2seq(encoder_inputs[:bucket[0]],
> -> 1206                                     decoder_inputs[:bucket[1]])
>    1207         outputs.append(bucket_outputs)
>    1208         if per_example_loss:
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in <lambda>(x, y)
>     176           self.encoder_inputs, self.decoder_inputs, targets,
>     177           self.target_weights, buckets,
> --> 178           lambda x, y: seq2seq_f(x, y, False),
>     179           softmax_loss_function=softmax_loss_function)
>     180 
> 
> ~/cookbook_py3/tensorflow_cookbook/09_Recurrent_Neural_Networks/05_Creating_A_Sequence_To_Sequence_Model/temp/tutorials/rnn/translate/seq2seq_model.py in seq2seq_f(encoder_inputs, decoder_inputs, do_decode)
>     140           output_projection=output_projection,
>     141           feed_previous=do_decode,
> --> 142           dtype=dtype)
>     143 
>     144     # Feeds for inputs.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py in embedding_attention_seq2seq(encoder_inputs, decoder_inputs, cell, num_encoder_symbols, num_decoder_symbols, embedding_size, num_heads, output_projection, feed_previous, dtype, scope, initial_state_attention)
>     846     dtype = scope.dtype
>     847     # Encoder.
> --> 848     encoder_cell = copy.deepcopy(cell)
>     849     encoder_cell = core_rnn_cell.EmbeddingWrapper(
>     850         encoder_cell,
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     159             copier = getattr(x, "__deepcopy__", None)
>     160             if copier:
> --> 161                 y = copier(memo)
>     162             else:
>     163                 reductor = dispatch_table.get(cls)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/site-packages/tensorflow/python/layers/base.py in __deepcopy__(self, memo)
>     474         setattr(result, k, copy.copy(v))
>     475       else:
> --> 476         setattr(result, k, copy.deepcopy(v, memo))
>     477     return result
>     478 
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_list(x, memo, deepcopy)
>     213     append = y.append
>     214     for a in x:
> --> 215         append(deepcopy(a, memo))
>     216     return y
>     217 d[list] = _deepcopy_list
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     178                     y = x
>     179                 else:
> --> 180                     y = _reconstruct(x, memo, *rv)
>     181 
>     182     # If is its own copy, don't memoize.
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
>     278     if state is not None:
>     279         if deep:
> --> 280             state = deepcopy(state, memo)
>     281         if hasattr(y, '__setstate__'):
>     282             y.__setstate__(state)
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     148     copier = _deepcopy_dispatch.get(cls)
>     149     if copier:
> --> 150         y = copier(x, memo)
>     151     else:
>     152         try:
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
>     238     memo[id(x)] = y
>     239     for key, value in x.items():
> --> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
>     241     return y
>     242 d[dict] = _deepcopy_dict
> 
> ~/anaconda2/envs/cookbook_py3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
>     167                     reductor = getattr(x, "__reduce_ex__", None)
>     168                     if reductor:
> --> 169                         rv = reductor(4)
>     170                     else:
>     171                         reductor = getattr(x, "__reduce__", None)
> 
> TypeError: can't pickle _thread.lock objects

I use ubuntu 16.04, tensorflow1.2.1, python3.6,

**Comment by ruyingghost** [comment]
same error

tensorflow1.3 python3.5.4

**Comment by maxim5** [comment]
@lyan62 @ruyingghost 

See [this answer on StackOverflow](https://stackoverflow.com/a/47952913/712995) and also https://github.com/tensorflow/tensorflow/issues/11157 . Basically, the workaround is this:

```python
setattr(tf.contrib.rnn.GRUCell, '__deepcopy__', lambda self, _: self)
setattr(tf.contrib.rnn.BasicLSTMCell, '__deepcopy__', lambda self, _: self)
setattr(tf.contrib.rnn.MultiRNNCell, '__deepcopy__', lambda self, _: self)
```

**Comment by nfmcclure** [comment]
HI @lyan62 and @ruyingghost , Sorry about the bug! (and the late reply).  I'm just now getting around to triaging the issues and updating the code.

@maxim5 , thanks for the fix.  I'll incorporate this (or the most current fix) in to the future code update in the next few months.

**Comment by nfmcclure** [comment]
This should be fixed now.  Please check the current code.  If you are still running into issues, feel free to re-open.  If you re-open, also post your Python and TensorFlow versions.  Thanks!
